### ISSUE TITLE
Screen tearing on Metal at high framerates

### ISSUE THREAD

**Issue by nSadd** [ppy/osu-framework#5736]
using the new metal renderer on an m1 mac (macOS 13.2.1, osu! 2023.403.1-lazer) results in really bad screentearing at high fps

you can't see it when screen recording, but it is glaringly obvious in person so i took this video (issue does not occur with openGL, only metal)

https://user-images.githubusercontent.com/53909427/230754465-c61967ba-84a8-4d6c-ba10-f81b43525842.mp4

**Comment by frenzibyte** [comment]
This has been improved/resolved now with `CADisplayLink` support.

**Comment by peppy** [comment]
*kind of*

As we found out late last week, tearing may still occur depending on game settings.

For any user looking to avoid tearing after 2023.605.0 (until we improve things at our end), please run the game in single thread mode, and optionally set your frame limiter to vsync.
